spring:
  application:
    name: expense-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/expense_db
    username: postgres
    password: Salam2024
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml